### ISSUE TITLE
Auth OIDC and Gitlab errors, but nothing in logs

### ISSUE THREAD

**Issue by nathanael-h** [freifunkMUC/wg-access-server#154]
Hello, 
I am trying to configure OIDC or Gitlab auth. 
The point is that I have for both I end with an error like this on web: 

```
server error
trace = 060dd72d-2072-40a2-8ea3-xxxxxxxxxxxx
```
But even with log level set to DEBUG I have nothing in the logs output of the wg-access-server container. 

So do you think I could have more logs to understand what is the error I have? Or maybe do you see any bad config I made?

Here is my config.yaml

```yaml
auth:
  oidc:
    name: "SSO CAS"
    issuer: "https://sso-preprod.aaa.fr/cas/oidc"
    clientID: "wireguard"
    clientSecret: "xxx"
    scopes:
      - openid
      - profile
      - email
    redirectURL: "https://vpn.aaa.fr/callback"
    claimMapping:
      admin: "'WireguardAdmins' in group_membership"
  gitlab:
    name: "Gitlab Preprod"
    baseURL: "https://git.aaa.fr"
    clientID: "xxxxxx"
    clientSecret: "yyyyyyy"
    redirectURL: "https://vpn.company.fr/callback"
    emailDomains:
      - aaa.fr
 ```
