### ISSUE TITLE
WG_DNS_ENABLED=false seems not to work

### ISSUE THREAD

**Issue by systems-levigo** [freifunkMUC/wg-access-server#205]
Hello there!
The environment variable `WG_DNS_ENABLED=false` seems not to work.
Our test installation is using docker-compose:
````
version: "3.0"
services:
  wg-access-server:
    image: ghcr.io/freifunkmuc/wg-access-server:latest
    container_name: wg-access-server
    cap_add:
      - NET_ADMIN
    volumes:
      - "wg-access-server-data:/data"
      - "./config.yaml:/data/config.yaml" 
    environment:
      - "WG_ADMIN_PASSWORD=sensored"
      - "WG_WIREGUARD_PRIVATE_KEY=sensored"
      - "WG_VPN_CIDRV6=0" # to disable IPv6
      - "WG_VPN_CLIENT_ISOLATION=false" # to disable traffic between client devices
      - "WG_CONFIG=/data/config.yaml"
      - "WG_EXTERNAL_HOST=sensored"
      - "WG_DNS_ENABLED=false"
      - "WG_IPV4_NAT_ENABLED=true"
      - "WG_VPN_GATEWAY_INTERFACE=eth0"
    ports:
      - "8000:8000/tcp"
      - "51820:51820/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
volumes:
  wg-access-server-data:
    driver: local
````
We set `WG_DNS_ENABLED=false` but our client configuration looks like this:
````
[Interface]
PrivateKey = sensored
Address = 10.44.0.4/32
DNS = 10.44.0.1

[Peer]
PublicKey = Sar4+dx08fS6EwvLfJztDMSwQBy3YqvKfBhVTk4Wi3Q=
AllowedIPs = 0.0.0.0/0, ::/0, 10.44.0.1/32
Endpoint = sensored:51820
````
Shouldn't the "DNS" variable be empty or are we doing something wrong?
Also the dns server is starting:
````
wg-access-server  | time="2022-06-17T10:57:44Z" level=info msg="starting wireguard server on :51820" file="main.go:123"
wg-access-server  | time="2022-06-17T10:57:44Z" level=info msg="wireguard VPN network is 10.44.0.1/24" file="main.go:138"
wg-access-server  | time="2022-06-17T10:57:44Z" level=info msg="storing data in SQL backend sqlite3" file="contracts.go:73"
wg-access-server  | time="2022-06-17T10:57:44Z" level=info msg="starting dns server on 10.44.0.1:53 with upstreams: 127.0.0.11" file="server.go:32"
wg-access-server  | time="2022-06-17T10:57:44Z" level=info msg="serving website from ./website/build" file="website_router.go:37"
wg-access-server  | time="2022-06-17T10:57:44Z" level=info msg="web ui listening on :8000" file="main.go:260"
````
In general we want to use the client resolver and sometimes we also need to override it.

Thank you! :)
