### ISSUE TITLE
ADFS as OIDC provider help

### ISSUE THREAD

**Issue by hooray4me** [freifunkMUC/wg-access-server#213]
I am trying to use my existing adfs setup for my oidc provider. I created an application group, client id and secret and DO have them talking... just not the same language...

```wg-access-server    | time="2022-06-27T21:07:01Z" level=error msg="Unable to get user info: 401 Unauthorized: " file="middleware.go:23" stack="goroutine 75 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24```

I am using fqdn/callback as the return uri... I don't know what do use in my issuance transform rules. Can someone help point me in the right direction?

config.yaml
```
auth:
  oidc:
    name: "ADFS OIDC Backend"
    issuer: "https://fs.domain.com/adfs"
    clientID: "4b7ac812-6055-47bb-xxxxx-xxxxxxxx"
    clientSecret: "XXXXXXXXXXXXMXXXXXXXXXXXXXXXXXXX"
    scopes:
      - openid
    redirectURL: "https://vpn.domain.com/callback"
    claimMapping:
      admin: "'ADFS_VPN_Admins' in group_membership"
```

![image](https://user-images.githubusercontent.com/12399138/176036997-b94f5d92-a14c-400d-a36b-503de1d24d6c.png)

![image](https://user-images.githubusercontent.com/12399138/176037024-f2b6a13c-6ed0-4440-8b8b-52495b3cde07.png)

![image](https://user-images.githubusercontent.com/12399138/176037056-4af740b0-3610-4dbc-a9c7-477e78248fda.png)
