### ISSUE TITLE
Failed to set ip address of wireguard interface: permission denied

### ISSUE THREAD

**Issue by nils1323** [freifunkMUC/wg-access-server#25]
Hey, I'm trying to setup the container with docker-compose. I also tried the docker version. Everything as root. Im getting the following trace:
```Creating volume "wg-access-server_wg-access-server-data" with local driver
Creating wg-access-server ... done
Attaching to wg-access-server
wg-access-server    | time="2021-11-21T22:22:46Z" level=info msg="starting wireguard server on :51820" file="main.go:101"
wg-access-server    | time="2021-11-21T22:22:46Z" level=fatal msg="failed to load wireguard config: failed to set interface ip address: failed to set ip address of wireguard interface: permission denied" file="main.go:112"
wg-access-server exited with code 1
```

The suggested "fast" setup is also not working and throws the same trace. 

Used Configs:
```version: "3.0"
services:
  wg-access-server:
    # to build the docker image from the source
    # build:
    #   dockerfile: Dockerfile
    #   context: .
    image: ghcr.io/freifunkmuc/wg-access-server:latest
    container_name: wg-access-server
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "wg-access-server-data:/data"
    #   - "./config.yaml:/config.yaml" # if you have a custom config file
    environment:
      - "WG_ADMIN_USERNAME=admin"
      - "WG_ADMIN_PASSWORD=admin"
      - "WG_WIREGUARD_PRIVATE_KEY=####"
      - "WG_EXTERNAL_HOST=wg.example.org"
      - "WG_VPN_CIDR=192.168.34.0/24"
      - "WG_VPN_GATEWAY_INTERFACE=ens19"
      - "WG_DNS_ENABLED=false"
      - "WG_VPN_ALLOWED_IPS=10.10.1.0/24,192.168.34.0/24"
      - "WG_PORT=51822"
      - "WG_WIREGUARD_INTERFACE=wg1"
      - "WG_LOG_LEVEL=trace"
    ports:
      - "8000:8000/tcp"
      - "51822:51822/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"

volumes:
  wg-access-server-data:
    driver: local
```
The peers are connecting through interface ens19 with a public IP and should be able to access interface ens18 with 10.10.1.0/24. 
operating System: debian 11 with latest updates
docker-version: 20.10.5

Furthermore all docker related configs are using the wrong URLs to the docker images. They are relating to `ghcr.io/freifunkmuc/wg-access-server/wg-access-server:latest` and not `ghcr.io/freifunkmuc/wg-access-server:latest` as they should.

**Comment by GoliathLabs** [comment]
Hi,
yes, we should work on our documentation.

Try adding
```
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
```

to your wireguard service in the docker-compose file.

Also, this should be added as well (as we're using IPv6, too)
```
  ipv6nat:
    restart: always
    image: robbertkl/ipv6nat:0.4.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro
    privileged: true
    network_mode: "host"
    security_opt:
      - label=disable
networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd00:0123:4568::/48
          gateway: fd00:0123:4568::1
```
