### ISSUE TITLE
VPN Routing not working

### ISSUE THREAD

**Issue by CookieCr2nk** [freifunkMUC/wg-access-server#59]
Hello Maintainers,

I deployed recently a test instance of the wg-access-server. I did exactly the following steps that are documentated on the documentation: "https://www.freie-netze.org/wg-access-server/deployment/2-docker-compose/".

1. Is it possible to use my own DNS IP's with the env variable WG_DNS_UPSTREAM, because my resolv.conf contains 127.0.0.53 which is the local dns-resolver of ubuntu.

2.  I can connect to the wireguard server, but i can only ping the wireguard server. It seems, that traffic is not routed correctly out of the container.

![image](https://user-images.githubusercontent.com/38990807/149187599-0833d908-e2c8-4dcb-84ca-d181ebca57cf.png)

OS: Ubuntu 20.04 LTS
Package: Wireguard installed via "apt install wireguard"

docker-compose.yml
```
version: "3.0"
services:
  wg-access-server:
    image: ghcr.io/freifunkmuc/wg-access-server:latest
    container_name: wg-access-server
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
    volumes:
      - ./wg_data:/data
    #   - "./config.yaml:/config.yaml" # if you have a custom config file
    environment:
      - WG_ADMIN_USERNAME=admin
      - WG_ADMIN_PASSWORD=<censored>
      - WG_WIREGUARD_PRIVATE_KEY=<censored>
      - WG_LOG_LEVEL=info
      - WG_PORT=8080
      - WG_EXTERNAL_HOST=<censored>
      - WG_DISABLE_METADATA=false
      - WG_WIREGUARD_INTERFACE=wg0
      - WG_WIREGUARD_PORT=5938
      - WG_VPN_CIDR=10.44.0.0/24
      - WG_VPN_CIDRV6=0
      - WG_IPV4_NAT_ENABLED=true
      - WG_IPV6_NAT_ENABLED=true
      - WG_VPN_GATEWAY_INTERFACE=ens160
      - WG_VPN_ALLOWED_IPS=0.0.0.0/0
      - WG_DNS_ENABLED=true
      - WG_DNS_UPSTREAM=172.64.36.1,172.64.36.2
    ports:
      - "8080:8080/tcp"
      - "5938:5938/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
```

docker logs
```
wg-access-server    | time="2022-01-12T16:55:53Z" level=info msg="starting wireguard server on :5938" file="main.go:112"
wg-access-server    | time="2022-01-12T16:55:53Z" level=info msg="wireguard VPN network is 10.44.0.1/24" file="main.go:126"
wg-access-server    | time="2022-01-12T16:55:53Z" level=info msg="starting dns server on :53 with upstreams: 172.64.36.1,172.64.36.2" file="server.go:33"
wg-access-server    | time="2022-01-12T16:55:53Z" level=info msg="storing data in SQL backend sqlite3" file="contracts.go:73"
wg-access-server    | time="2022-01-12T16:55:53Z" level=info msg="serving website from ./website/build" file="website_router.go:37"
wg-access-server    | time="2022-01-12T16:55:53Z" level=info msg="web ui listening on :8080" file="main.go:214"
wg-access-server    | time="2022-01-12T16:56:08Z" level=info msg="finished unary call with code OK" file="options.go:220" grpc.code=OK grpc.method=Info grpc.service=proto.Server grpc.start_time="2022-01-12T16:56:08Z" grpc.time_ms=0.708 span.kind=server system=grpc trace.id=6c339c00-6d07-44fd-85f6-0946ae56ff88
wg-access-server    | time="2022-01-12T16:56:08Z" level=info msg="finished unary call with code OK" file="options.go:220" grpc.code=OK grpc.method=ListDevices grpc.service=proto.Devices grpc.start_time="2022-01-12T16:56:08Z" grpc.time_ms=0.653 span.kind=server system=grpc trace.id=fdcb70fb-42ca-4e30-939b-a12a6f9f370d
wg-access-server    | time="2022-01-12T16:56:13Z" level=info msg="finished unary call with code OK" file="options.go:220" grpc.code=OK grpc.method=AddDevice grpc.service=proto.Devices grpc.start_time="2022-01-12T16:56:13Z" grpc.time_ms=4.784 span.kind=server system=grpc trace.id=a639de18-2e8d-41d9-a2bd-34134ea29614
wg-access-server    | time="2022-01-12T16:56:14Z" level=info msg="finished unary call with code OK" file="options.go:220" grpc.code=OK grpc.method=ListDevices grpc.service=proto.Devices grpc.start_time="2022-01-12T16:56:14Z" grpc.time_ms=0.667 span.kind=server system=grpc trace.id=db32c264-54a3-4189-b3b2-89a60abb9c67
wg-access-server    | time="2022-01-12T16:56:38Z" level=info msg="finished unary call with code OK" file="options.go:220" grpc.code=OK grpc.method=ListDevices grpc.service=proto.Devices grpc.start_time="2022-01-12T16:56:38Z" grpc.time_ms=0.694 span.kind=server system=grpc trace.id=fd6f8c5d-4ce9-44bf-a864-6ce0b04411d0
wg-access-server    | time="2022-01-12T16:57:08Z" level=info msg="finished unary call with code OK" file="options.go:220" grpc.code=OK grpc.method=ListDevices grpc.service=proto.Devices grpc.start_time="2022-01-12T16:57:08Z" grpc.time_ms=0.715 span.kind=server system=grpc trace.id=c6d5f9b2-15c9-483d-ac11-773a9cf6e86c
wg-access-server    | time="2022-01-12T16:57:35Z" level=warning msg="DNS lookup failed for upstream 172.64.36.1,172.64.36.2: dial udp: lookup 172.64.36.1,172.64.36.2: no such host" file="server.go:122"wg-access-server    | time="2022-01-12T16:57:35Z" level=error msg="failed lookup record with error: dial udp: lookup 172.64.36.1,172.64.36.2: no such host\n;; opcode: QUERY, status: NOERROR, id: 2650\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;vault.bitwarden.com.\tIN\t A\n" file="server.go:76"
wg-access-server    | time="2022-01-12T16:57:35Z" level=warning msg="DNS lookup failed for upstream 172.64.36.1,172.64.36.2: dial udp: lookup 172.64.36.1,172.64.36.2: no such host" file="server.go:122"wg-access-server    | time="2022-01-12T16:57:35Z" level=error msg="failed lookup record with error: dial udp: lookup 172.64.36.1,172.64.36.2: no such host\n;; opcode: QUERY, status: NOERROR, id: 4743\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;sdk.split.io.\tIN\t A\n" file="server.go:76"
wg-access-server    | time="2022-01-12T16:57:35Z" level=warning msg="DNS lookup failed for upstream 172.64.36.1,172.64.36.2: dial udp: lookup 172.64.36.1,172.64.36.2: no such host" file="server.go:122"wg-access-server    | time="2022-01-12T16:57:35Z" level=error msg="failed lookup record with error: dial udp: lookup 172.64.36.1,172.64.36.2: no such host\n;; opcode: QUERY, status: NOERROR, id: 54036\n;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0\n\n;; QUESTION SECTION:\n;www.msftconnecttest.com.\tIN\t A\n" file="server.go:76"
wg-access-server    | time="2022-01-12T16:57:35Z" level=warning msg="DNS lookup failed for upstream 172.64.36.1,172.64.36.2: dial udp: lookup 172.64.36.1,172.64.36.2: no such host" file="server.go:122"wg-access-server    | time="2022-01-12T16:57:35Z" level=error msg="failed lookup record with error: dial udp: lookup 172.64.36.1,172.64.36.2: no such host\n;; opcode: QUERY, status: NOERROR, id: 27188\
```

**Comment by GoliathLabs** [comment]
Regarding the DNS lookup, try to specify only one IP (e.g. `WG_DNS_UPSTREAM=172.64.36.1`)

**Comment by GoliathLabs** [comment]
Can you show us a generated client config (omit sensitive values)?

**Comment by DasSkelett** [comment]
```yaml
WG_VPN_GATEWAY_INTERFACE=ens160
```
This looks suspicious. You are running it inside Docker, and as far as I know, inside the container the default interface is always named `eth0`.
Try leaving this variable undefined to let the automated detection take care of it, and see if it works then.

And yeah, for the DNS upstream, it looks like the splitting when reading from environment variables doesn't work.
I'll look into a fix for that, but as a workaround you could either only specify one upstream address, or pass them as two command arguments:
```
command: wg-access-server serve --dns-upstream=1.1.1.1 --dns-upstream=9.9.9.9
```

**Comment by CookieCr2nk** [comment]
Thx for the fast answer. So misunderstanding on my site. I expected that the variable "WG_VPN_GATEWAY_INTERFACE" needs the physical Interface.

I'm Happy 👍

My actually Configuration that is working now. -> 

docker-compose.yml
```
version: "3.0"
services:
  wg-access-server:
    image: ghcr.io/freifunkmuc/wg-access-server:latest
    container_name: wg-access-server
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
    volumes:
      - ./wg_data:/data
    #   - "./config.yaml:/config.yaml" # if you have a custom config file
    environment:
      - WG_ADMIN_USERNAME=admin
      - WG_ADMIN_PASSWORD=<censored>
      - WG_WIREGUARD_PRIVATE_KEY=<censored>
      - WG_LOG_LEVEL=info
      - WG_PORT=8080
      - WG_EXTERNAL_HOST=<censored>
      - WG_DISABLE_METADATA=false
      - WG_WIREGUARD_INTERFACE=wg0
      - WG_WIREGUARD_PORT=5938
      - WG_VPN_CIDR=10.44.0.0/24
      - WG_VPN_CIDRV6=0
      - WG_IPV4_NAT_ENABLED=true
      - WG_IPV6_NAT_ENABLED=true
      - WG_VPN_GATEWAY_INTERFACE=eth0
      - WG_VPN_ALLOWED_IPS=0.0.0.0/0
      - WG_DNS_ENABLED=true
      - WG_DNS_UPSTREAM=172.64.36.1
    ports:
      - "8080:8080/tcp"
      - "5938:5938/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
```
