### ISSUE TITLE
Helm chart with ingress fails to install - no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by nodesocket** [freifunkMUC/wg-access-server#65]
```shell
pi@kube-master: $ helm install wg-access-server --values wg-access-server.yaml --repo https://place1.github.io/wg-access-server wg-access-server
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
````

Contents of `wg-access-server.yaml` is:

```yaml
wireguard:
  config:
    privateKey: "super-secret-here"

persistence:
  enabled: true
  size: 1Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
  hosts:
    - vpn.hooli.xyz
  tls:
    - hosts:
        - vpn.hooli.xyz
```

### Environment

Raspberry Pi running Debian GNU/Linux 11 (bullseye) linux/arm64

```shell
pi@kube-master: $ helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

pi@kube-master: $ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/arm64"}
```
