### ISSUE TITLE
no ipv6 support as connected client

### ISSUE THREAD

**Issue by maurerle** [freifunkMUC/wg-access-server#793]
While ipv4 works fine, somehow ipv6 does not work for clients out of the box on a bookworm server having latest docker installed.

docker compose file:
```
  wg-access-server:
    image: ghcr.io/freifunkmuc/wg-access-server
    restart: always
    env_file: .env
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
    volumes:
      - "./data:/data"
    ports:
      - "80:80"
      - "51820:51820/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
```

the client:
```
interface: wg-ffac
  public key: (hidden)
  private key: (hidden)
  listening port: 52796
  fwmark: 0xca6c

peer: (hidden)
  endpoint: [hidden]:51820
  allowed ips: 0.0.0.0/0, ::/0, 10.44.0.3/32, fd48:4c4:7aa9::3/128
  latest handshake: 50 seconds ago
  transfer: 27.74 MiB received, 2.24 MiB sent
➜  ~ ping fd48:4c4:7aa9::1
PING fd48:4c4:7aa9::1 (fd48:4c4:7aa9::1) 56 data bytes
64 bytes from fd48:4c4:7aa9::1: icmp_seq=1 ttl=64 time=39.2 ms
64 bytes from fd48:4c4:7aa9::1: icmp_seq=2 ttl=64 time=23.8 ms
64 bytes from fd48:4c4:7aa9::1: icmp_seq=3 ttl=64 time=106 ms
^C
--- fd48:4c4:7aa9::1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 23.831/56.460/106.332/35.819 ms
➜  ~ ping -6 heise.de            
PING heise.de (2a02:2e0:3fe:1001:302::) 56 data bytes
From fd48:4c4:7aa9::1 icmp_seq=1 Destination unreachable: No route
From fd48:4c4:7aa9::1 icmp_seq=2 Destination unreachable: No route
```

inside the docker container:

```
sudo docker compose exec wg-access-server bash
5ae4c9841c00:/# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host proto kernel_lo 
       valid_lft forever preferred_lft forever
2: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.44.0.1/24 brd 10.44.0.255 scope global wg0
       valid_lft forever preferred_lft forever
    inet6 fd48:4c4:7aa9::1/64 scope global 
       valid_lft forever preferred_lft forever
18: eth0@if19: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:12:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.0.2/16 brd 172.18.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:2/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever

ip6tables-save
# Generated by ip6tables-save v1.8.10 (nf_tables) on Tue Jan 14 07:26:26 2025
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:WG_ACCESS_SERVER_FORWARD - [0:0]
-A FORWARD -j WG_ACCESS_SERVER_FORWARD
-A WG_ACCESS_SERVER_FORWARD -s fd48:4c4:7aa9::/64 -j ACCEPT
-A WG_ACCESS_SERVER_FORWARD -s fd48:4c4:7aa9::/64 -d fd48:4c4:7aa9::1/128 -j ACCEPT
-A WG_ACCESS_SERVER_FORWARD -s fd48:4c4:7aa9::/64 -j REJECT --reject-with icmp6-port-unreachable
COMMIT
# Completed on Tue Jan 14 07:26:26 2025
# Generated by ip6tables-save v1.8.10 (nf_tables) on Tue Jan 14 07:26:26 2025
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:WG_ACCESS_SERVER_POSTROUTING - [0:0]
-A POSTROUTING -j WG_ACCESS_SERVER_POSTROUTING
-A WG_ACCESS_SERVER_POSTROUTING -s fd48:4c4:7aa9::/64 -o eth0 -j MASQUERADE
COMMIT
# Completed on Tue Jan 14 07:26:26 2025
```

Looks fine for me - postrouting is enabled but something does not work. Any ideas?
Do I need to execute anything on the docker host?

**Comment by maurerle** [comment]
So I found, that one needs to add ipv6 to the docker compose for it to work.
A working compose.yml is given here:

```yml
services:
  wg-access-server:
    image: ghcr.io/freifunkmuc/wg-access-server
    restart: always
    env_file: .env
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
    volumes:
      - "./data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wg-access-server.rule=Host(`ffac.felixevers.de`)"
      - "traefik.http.routers.wg-access-server.entrypoints=websecure"
      - "traefik.http.routers.wg-access-server.tls=true"
      - "traefik.http.routers.wg-access-server.tls.certresolver=resolver"
    expose:
      - 80
    ports:
      - "51820:51820/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: fd47:ca44:ab18:d9cf::10

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: fd47:ca44:ab18:d9cf::/64
        gateway: fd47:ca44:ab18:d9cf::1
```

So I'll close this issue.
Maybe we should update the docs on this :)
