### ISSUE TITLE
Non-TLS Admin Access Options

### ISSUE THREAD

**Issue by FrankBlackMG** [freifunkMUC/wg-access-server#854]
With the latest release it looks like you cannot access the admin GUI without an SSL/TLS reverse proxy in front of wg-access-server. The docs show a sample compose file where a letsencrypt sample config is shown. I only need to access the GUI admin from the local LAN of the server. No internet access. I have no need of TLS.

What exactly is requiring the TLS proxy and how does it know there is a proxy?

Is there a sample where a self-signed cert is used without needing letsencrypt? Or even better, a way to not require TLS at all for LAN access.

**Comment by nocin** [comment]
I am wondering the same. I'm using the container in an LXC on my Proxmox server at home, and therefore I don't have the need for SSL for any of my local services. Maybe a new environment variable/configuration option can be introduced to disable it again?

**Comment by GoliathLabs** [comment]
Due to a dependency update, the authentication cookie is now set to 'Secure'.
This means HTTP access is limited to localhost only, while all remote authentication requires HTTPS.
We have added an [example](https://www.freie-netze.org/wg-access-server/deployment/2-docker-compose/#with-traefik-as-reverse-proxy) for Docker Compose deployment with Traefik.

As of now, you'd have to use a local reverse proxy with (self-signed) TLS enabled.

**Comment by T0biii** [comment]
@FrankBlackMG @nocin 
if you access the gui via http://localhost it should work fine, but then it maybe hosted on the same machine, can you test if ssh port forwarding to localhost works?

you can use a self signed cert we currently dont have an example for this, you can use any reverse proxy you like. 
For treafik you got docs here for TLS: https://doc.traefik.io/traefik/https/tls/#user-defined
Maybe i can later add an example for self signed cert

**Comment by T0biii** [comment]
You can just remove the letsencrypt entry from treafik

```yaml
services:
  wg-access-server:
    # to build the docker image from the source
    # build:
    #   dockerfile: Dockerfile
    #   context: .
    image: ghcr.io/freifunkmuc/wg-access-server:latest
    container_name: wg-access-server
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
    volumes:
      - "wg-access-server-data:/data"
    #   - "./config.yaml:/config.yaml" # if you have a custom config file
    environment:
      - "WG_ADMIN_PASSWORD=adminpassword"
      - "WG_WIREGUARD_PRIVATE_KEY=privatekey"
    #  - "WG_VPN_CIDRV6=0" # to disable IPv6
    expose:
      - "8000/tcp"
    ports:
      - "51820:51820/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    depends_on:
      - reverse-proxy
    labels:
      - traefik.http.routers.vpn.rule=Host(`vpn.example.com`)
      - traefik.http.routers.vpn.tls=true

  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3
    command: >
      --providers.docker
      --entryPoints.websecure.address=:443
    ports:
      # The HTTP/HTTPS ports
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

# shared volumes with the host
volumes:
  wg-access-server-data:
    driver: local
```

Then you automatically get a default certificate from Traefik:

![Image](https://github.com/user-attachments/assets/5d32f743-8331-410b-b19e-b0d67d332709)

```yaml
- traefik.http.routers.vpn.rule=Host(`vpn.example.com`)`
```
you can also replace with an ip
```yaml
- traefik.http.routers.vpn.rule=Host(`192.168.100.1`) 
```

**Comment by nocin** [comment]
This worked, thank you @T0biii! 
This should really be added to the [example](https://www.freie-netze.org/wg-access-server/deployment/2-docker-compose/#with-traefik-as-reverse-proxy) section, as I guess many people are using the docker container in their homelab and will only access the web interface from their local network.

**Comment by T0biii** [comment]
PRs for other Reverse Proxy also very welcome :)

**Comment by T0biii** [comment]
https://github.com/freifunkMUC/wg-access-server/pull/878 

Enables HTTPS for the project on port 8443 when the PR gets merged.
Maybe someone can test the :master Docker image afterwards — it worked fine for me.

HTTPS will be enabled by default but can be disabled if needed.

**Comment by T0biii** [comment]
https://github.com/freifunkMUC/wg-access-server/pull/878

Enables HTTPS for the project on port 8443 when the PR gets merged.
Maybe someone can test the :master Docker image afterwards — it worked fine for me.

HTTPS will be enabled by default but can be disabled if needed.

**Comment by T0biii** [comment]
PR #878 is now merged. 
When port `8443` is set in Docker Compose, the app serves HTTPS directly - no reverse proxy needed to simplify HomeLabs Setup. However, I'd still recommend using a reverse proxy if you already have one, then you can Disable the HTTPS Server of wg-access-server.

You can change HTTPS seetings see [docs](https://www.freie-netze.org/wg-access-server/2-configuration/):

![Image](https://github.com/user-attachments/assets/5cc5bbba-baaa-472e-a4fe-f483f0519874)


with `ghcr.io/freifunkmuc/wg-access-server:master` you can get the newest version with build in HTTPS Server, if the Github Action: https://github.com/freifunkMUC/wg-access-server/actions/runs/14326270883 is done.
`master` should only be used for testing. A release will surely follow in the next few days.

**Comment by FrankBlackMG** [comment]
@T0biii , Thank you very much for the WG_HTTPS_ENABLED option. I pulled the docker image with latest hash (I'm not sure your changes are in there). This did not work for me. Here is my compose file and a log snippet. Let me know if I'm missing something. The secure cookie option is obviously still there in dev tools.

One other question on the https option. When I first tried this with12.1, it would take me to the login screen but not accept my password. No error message, it just re-prompts for username/password. I would think you wouldn't want any login page to appear if it's not over a secure connection.

This same behavior is what happens with my setup below. Re-prompt for username/password with no UI message and no log message.

```
services:
  wg-access-server:
    #image: ghcr.io/freifunkmuc/wg-access-server:latest
    #image: ghcr.io/freifunkmuc/wg-access-server:v0.12.1
    image: ghcr.io/freifunkmuc/wg-access-server:sha-4d4e0eb
    container_name: wg-access-server
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - "./volume/data:/data"
    #   - "./config.yaml:/config.yaml" # if you have a custom config file
    environment:
      - "WG_ADMIN_PASSWORD=${WG_ADMIN_PASSWORD}"
      - "WG_WIREGUARD_PRIVATE_KEY=${WG_WIREGUARD_PRIVATE_KEY}"
      - "WG_EXTERNAL_HOST=${WG_EXTERNAL_HOST}"
      - "WG_WIREGUARD_PORT=${WG_WIREGUARD_PORT}"
      - "WG_VPN_CIDR=${WG_VPN_CIDR}"
      - "WG_VPN_CLIENT_ISOLATION=${WG_VPN_CLIENT_ISOLATION}"
      - "WG_VPN_ALLOWED_IPS=${WG_VPN_ALLOWED_IPS}"
      - "WG_VPN_CIDRV6=0" # to disable IPv6
      - "WG_HTTPS_ENABLED=false" # to disable HTTPS
    ports:
      - "8001:8000/tcp"
      - "NNNN:NNNN/udp" #Masked for posting.
    devices:
      - "/dev/net/tun:/dev/net/tun"
```
This is the log:
```
wg-access-server  | time="2025-04-12T12:18:54Z" level=info msg="+++ wg-access-server master (4d4e0eb)" file="main.go:97"
wg-access-server  | time="2025-04-12T12:18:54Z" level=info msg="Starting WireGuard on :54321" file="main.go:144"
wg-access-server  | time="2025-04-12T12:18:54Z" level=info msg="WireGuard VPN network is 10.0.0.1/24" file="main.go:160"
wg-access-server  | time="2025-04-12T12:18:54Z" level=info msg="Storing data in SQL backend at sqlite3:///data/db.sqlite3" file="contracts.go:79"
wg-access-server  | time="2025-04-12T12:18:54Z" level=info msg="Starting DNS server on 10.0.0.1:53/udp, 10.0.0.1:53/tcp with upstreams: 127.0.0.11" file="server.go:95"
wg-access-server  | time="2025-04-12T12:18:54Z" level=info msg="Start collecting device metadata" file="devices.go:67"
wg-access-server  | time="2025-04-12T12:18:54Z" level=info msg="Serving website from ./website/build" file="website_router.go:37"
wg-access-server  | time="2025-04-12T12:18:54Z" level=info msg="Web UI listening on http://:8000" file="main.go:285"
wg-access-server  | time="2025-04-12T12:19:45Z" level=info msg="Creating web session with provider 'simple' for user 'admin' (remote address: 192.168.1.1:NNNNN)" file="session.go:46"
wg-access-server  | time="2025-04-12T12:19:50Z" level=info msg="Creating web session with provider 'simple' for user 'admin' (remote address: 192.168.1.1:NNNNN)" file="session.go:46"
```

**Comment by T0biii** [comment]
@FrankBlackMG the change is currently only on ":master" Image Tag. But `sha-4d4e0eb` seems to be also ok.
in youre example you disabled https so there is no https enabled, 
the https port would also be a different then instead of `8000` it would be `8443`

> I would think you wouldn't want any login page to appear if it's not over a secure connection. 

if you enable https and use the different port there would only https request accepted. 

http cant be disabled at the moment, as we prefer a reverse Proxy to offload https and also you can login via http only via localhost.


for https also on the exposed port 8001:
```yaml
services:
  wg-access-server:
    #image: ghcr.io/freifunkmuc/wg-access-server:latest
    #image: ghcr.io/freifunkmuc/wg-access-server:v0.12.1
    image: ghcr.io/freifunkmuc/wg-access-server:sha-4d4e0eb
    container_name: wg-access-server
    restart: always
    cap_add:
      - NET_ADMIN
    volumes:
      - "./volume/data:/data"
    #   - "./config.yaml:/config.yaml" # if you have a custom config file
    environment:
      - "WG_ADMIN_PASSWORD=${WG_ADMIN_PASSWORD}"
      - "WG_WIREGUARD_PRIVATE_KEY=${WG_WIREGUARD_PRIVATE_KEY}"
      - "WG_EXTERNAL_HOST=${WG_EXTERNAL_HOST}"
      - "WG_WIREGUARD_PORT=${WG_WIREGUARD_PORT}"
      - "WG_VPN_CIDR=${WG_VPN_CIDR}"
      - "WG_VPN_CLIENT_ISOLATION=${WG_VPN_CLIENT_ISOLATION}"
      - "WG_VPN_ALLOWED_IPS=${WG_VPN_ALLOWED_IPS}"
      - "WG_VPN_CIDRV6=0" # to disable IPv6
    ports:
      - "8001:8443/tcp"
      - "NNNN:NNNN/udp" #Masked for posting.
    devices:
      - "/dev/net/tun:/dev/net/tun"
```
